Use local GCC 8 for building native packages
Requires:

  sudo apt install g++-8-multilib

Error with GCC 9 in the linux-stable package was:

  | cstdlib:259:2: error: #endif without #if
  |   259 | #endif // !_GLIBCXX_HOSTED
  |       |  ^~~~~
  | cstdlib:129:1: error: '_ALLOC' does not name a type; did you mean 'CPU_ALLOC'?
  |   129 |
  |       | ^
  |       | CPU_ALLOC
  | stdlib.h:38:12: error: 'std::abort' has not been declared
  |    38 | using std::abort;
  |       |            ^~~~~