u-boot: Update to Python 3
Fixes error when Python 2 is blacklisted:

ERROR: Nothing PROVIDES 'python-native' (but u-boot_2019.07.bb DEPENDS on or otherwise requires it)
python-native was skipped: Recipe is blacklisted: Python 2 is not supported.