qemu: Update from v3.1.0 to v4.1.0 to fix build error
Error was:

  | syscall.c:253:16: error: static declaration of ‘gettid’ follows non-static declaration
  |   253 | _syscall0(int, gettid)
  |       |                ^~~~~~